package com.civicfix.util

import android.content.Context
import android.content.Intent
import android.graphics.*
import android.graphics.pdf.PdfDocument
import android.os.Environment
import androidx.core.content.FileProvider
import com.civicfix.domain.model.Issue
import java.io.File
import java.io.FileOutputStream

object PdfExporter {

    fun export(context: Context, issue: Issue) {
        val doc  = PdfDocument()
        val info = PdfDocument.PageInfo.Builder(595, 842, 1).create()
        val page = doc.startPage(info)
        val canvas = page.canvas

        val bgPaint = Paint().apply { color = Color.parseColor("#0A1628") }
        canvas.drawRect(0f, 0f, 595f, 842f, bgPaint)

        val headerPaint = Paint().apply { color = Color.parseColor("#0F2040") }
        canvas.drawRect(0f, 0f, 595f, 80f, headerPaint)

        val accentPaint = Paint().apply {
            color = Color.parseColor("#00D4FF")
            strokeWidth = 3f
            style = Paint.Style.STROKE
        }
        canvas.drawLine(0f, 80f, 595f, 80f, accentPaint)

        val titlePaint = Paint().apply {
            color = Color.WHITE
            textSize = 24f
            typeface = Typeface.DEFAULT_BOLD
        }
        canvas.drawText("CivicFix — Issue Report", 30f, 50f, titlePaint)

        val mutedPaint = Paint().apply { color = Color.parseColor("#8892A4"); textSize = 13f }
        val whitePaint = Paint().apply { color = Color.WHITE; textSize = 14f }
        val accentText = Paint().apply { color = Color.parseColor("#00D4FF"); textSize = 13f }

        var y = 110f
        fun row(label: String, value: String) {
            canvas.drawText(label, 30f, y, mutedPaint)
            canvas.drawText(value, 180f, y, whitePaint)
            y += 26f
        }

        row("Issue ID:",  "#${issue.id}")
        row("Title:",     issue.title.take(60))
        row("Category:",  issue.category)
        row("Status:",    issue.status)
        row("Priority:",  issue.priority)
        row("Reporter:",  issue.reporterName ?: "Unknown")
        row("Location:",  issue.address ?: "${issue.latitude}, ${issue.longitude}")
        row("Reported:",  issue.createdAt.take(10))
        row("Votes:",     "${issue.voteCount}")

        y += 10f
        val divPaint = Paint().apply { color = Color.parseColor("#162A52"); strokeWidth = 1f }
        canvas.drawLine(30f, y, 565f, y, divPaint)
        y += 20f

        canvas.drawText("Description", 30f, y, accentText)
        y += 20f
        issue.description.chunked(80).take(6).forEach { line ->
            canvas.drawText(line, 30f, y, whitePaint)
            y += 20f
        }

        val footerPaint = Paint().apply {
            color = Color.parseColor("#8892A4"); textSize = 11f
        }
        canvas.drawText("Generated by CivicFix · ${java.util.Date()}", 30f, 800f, footerPaint)

        doc.finishPage(page)

        try {
            val baseDir = context.getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS)
                ?: context.filesDir
            val dir  = File(baseDir, "CivicFix").also { it.mkdirs() }
            val file = File(dir, "issue_${issue.id}_${System.currentTimeMillis()}.pdf")
            doc.writeTo(FileOutputStream(file))
            doc.close()

            val uri = FileProvider.getUriForFile(
                context, "${context.packageName}.provider", file
            )
            val intent = Intent(Intent.ACTION_VIEW).apply {
                setDataAndType(uri, "application/pdf")
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }
            context.startActivity(Intent.createChooser(intent, "Open PDF"))
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
}
